author:
  name: Timothy Ford
baseURL: timothywford.com
languageCode: en
menu:
  main:
    - name: About
      url: /about
params:
  description: Personal site for Timothy Ford.
title: Timothy Ford
theme: Blogpaper
